

--MAX HOTEL PRICE
SELECT TOP 1 Hotel_Name, MAX(Price_Per_Night) AS MAXHOTELPRICE FROM Hotel GROUP BY Hotel_Name ORDER BY MAXHOTELPRICE DESC;

--MIN HOTEL PRICE
SELECT TOP 1 Hotel_Name, MIN(Price_Per_Night) AS MINHOTELPRICE FROM Hotel GROUP BY Hotel_Name ORDER BY MINHOTELPRICE;

